# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "mvsas" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/f73b0100-e5ef-4f18-b308-bc832cef43b4";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/D97D-7181";
      fsType = "vfat";
    };

  fileSystems."/disks/storage1" =
    { device = "storage1";
      fsType = "zfs";
      options = [ "nofail" ];
    };

  fileSystems."/disks/storage1/coleson" =
    { device = "storage1/coleson";
      fsType = "zfs";
      options = [ "nofail" ];
    };

  fileSystems."/disks/storage1/raelynn" =
    { device = "storage1/raelynn";
      fsType = "zfs";
      options = [ "nofail" ];
    };

  fileSystems."/disks/storage1/sham" =
    { device = "storage1/sham";
      fsType = "zfs";
      options = [ "nofail" ];
    };

  fileSystems."/disks/storage1/snapshots" =
    { device = "storage1/snapshots";
      fsType = "zfs";
      options = [ "nofail" ];
    };

  fileSystems."/disks/storage1/thorin" =
    { device = "storage1/thorin";
      fsType = "zfs";
      options = [ "nofail" ];
    };

  fileSystems."/disks/storage0" =
    { device = "storage0";
      fsType = "zfs";
      options = [ "nofail" ];
    };

  fileSystems."/disks/storage0/minecraft-asstown" =
    { device = "storage0/minecraft-asstown";
      fsType = "zfs";
      options = [ "nofail" ];
    };

  fileSystems."/disks/storage0/minecraft-dnd" =
    { device = "storage0/minecraft-dnd";
      fsType = "zfs";
      options = [ "nofail" ];
    };

  fileSystems."/disks/storage0/minecraft-n-world" =
    { device = "storage0/minecraft-n-world";
      fsType = "zfs";
      options = [ "nofail" ];
    };

  fileSystems."/disks/storage0/minecraft-sadworld" =
    { device = "storage0/minecraft-sadworld";
      fsType = "zfs";
      options = [ "nofail" ];
    };

  fileSystems."/disks/storage0/win-srv-2019" =
    { device = "storage0/win-srv-2019";
      fsType = "zfs";
      options = [ "nofail" ];
    };

  fileSystems."/disks/storage0/win10" =
    { device = "storage0/win10";
      fsType = "zfs";
      options = [ "nofail" ];
    };

  fileSystems."/disks/storage2" =
    { device = "storage2";
      fsType = "zfs";
      options = [ "nofail" ];
    };

  fileSystems."/disks/storage2/backups" =
    { device = "storage2/backups";
      fsType = "zfs";
      options = [ "nofail" ];
    };

  fileSystems."/disks/storage2/books" =
    { device = "storage2/books";
      fsType = "zfs";
      options = [ "nofail" ];
    };

  fileSystems."/disks/storage2/documents" =
    { device = "storage2/documents";
      fsType = "zfs";
      options = [ "nofail" ];
    };

  fileSystems."/disks/storage2/music" =
    { device = "storage2/music";
      fsType = "zfs";
      options = [ "nofail" ];
    };

  fileSystems."/disks/storage2/pictures" =
    { device = "storage2/pictures";
      fsType = "zfs";
      options = [ "nofail" ];
    };

  fileSystems."/disks/storage2/torrents" =
    { device = "storage2/torrents";
      fsType = "zfs";
      options = [ "nofail" ];
    };

  fileSystems."/disks/storage2/videos" =
    { device = "storage2/videos";
      fsType = "zfs";
      options = [ "nofail" ];
    };

  fileSystems."/disks/storage2/videos-share" =
    { device = "storage2/videos-share";
      fsType = "zfs";
      options = [ "nofail" ];
    };

  fileSystems."/disks/ssd0" =
    { device = "ssd0";
      fsType = "zfs";
      options = [ "nofail" ];
    };

  fileSystems."/disks/ssd0/freepbx" =
    { device = "ssd0/freepbx";
      fsType = "zfs";
      options = [ "nofail" ];
    };

  fileSystems."/disks/ssd0/opnsense" =
    { device = "ssd0/opnsense";
      fsType = "zfs";
      options = [ "nofail" ];
    };

  fileSystems."/disks/ssd0/vpnopnsense" =
    { device = "ssd0/vpnopnsense";
      fsType = "zfs";
      options = [ "nofail" ];
    };

  fileSystems."/disks/ssd-raid0-0" =
    { device = "ssd-raid0-0";
      fsType = "zfs";
      options = [ "nofail" ];
    };

  fileSystems."/disks/ssd-raid0-0/minecraft-asstown" =
    { device = "ssd-raid0-0/minecraft-asstown";
      fsType = "zfs";
      options = [ "nofail" ];
    };

  fileSystems."/disks/ssd-raid0-0/minecraft-dnd" =
    { device = "ssd-raid0-0/minecraft-dnd";
      fsType = "zfs";
      options = [ "nofail" ];
    };

  fileSystems."/disks/ssd-raid0-0/minecraft-n-world" =
    { device = "ssd-raid0-0/minecraft-n-world";
      fsType = "zfs";
      options = [ "nofail" ];
    };

  fileSystems."/disks/ssd-raid0-0/minecraft-sadworld" =
    { device = "ssd-raid0-0/minecraft-sadworld";
      fsType = "zfs";
      options = [ "nofail" ];
    };

  fileSystems."/disks/ssd-raid0-0/win-srv-2019" =
    { device = "ssd-raid0-0/win-srv-2019";
      fsType = "zfs";
      options = [ "nofail" ];
    };

  fileSystems."/disks/ssd-raid0-0/win10" =
    { device = "ssd-raid0-0/win10";
      fsType = "zfs";
      options = [ "nofail" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/7ff0498b-c609-4a8c-a20c-11b081ba9a8c"; }
    ];

}
