# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "mvsas" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/f73b0100-e5ef-4f18-b308-bc832cef43b4";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/D97D-7181";
      fsType = "vfat";
    };


  fileSystems."/disks/storage1" = 
    { device = "storage1/safe";
      fsType = "zfs";
      options = [ "nofail" ];
    };

  fileSystems."/disks/storage1/vms" = 
    { device = "storage1/safe/vms";
      fsType = "zfs";
      options = [ "nofail" ];
    };

  fileSystems."/disks/storage1/secrets" = 
    { device = "storage1/safe/secrets";
      fsType = "zfs";
      options = [ "nofail" ];
    };

  fileSystems."/disks/storage1/backups" = 
    { device = "storage1/safe/backups";
      fsType = "zfs";
      options = [ "nofail" ];
    };

  fileSystems."/disks/storage1/books" = 
    { device = "storage1/safe/books";
      fsType = "zfs";
      options = [ "nofail" ];
    };

  fileSystems."/disks/storage1/documents" = 
    { device = "storage1/safe/documents";
      fsType = "zfs";
      options = [ "nofail" ];
    };

  fileSystems."/disks/storage1/music" = 
    { device = "storage1/safe/music";
      fsType = "zfs";
      options = [ "nofail" ];
    };

  fileSystems."/disks/storage1/pictures" = 
    { device = "storage1/safe/pictures";
      fsType = "zfs";
      options = [ "nofail" ];
    };

  fileSystems."/disks/storage1/torrents" = 
    { device = "storage1/safe/torrents";
      fsType = "zfs";
      options = [ "nofail" ];
    };

  fileSystems."/disks/storage1/videos-share" = 
    { device = "storage1/safe/videos-share";
      fsType = "zfs";
      options = [ "nofail" ];
    };

  fileSystems."/disks/ssd0" =
    { device = "ssd0";
      fsType = "zfs";
      options = [ "nofail" ];
    };

  fileSystems."/disks/ssd0/freepbx" =
    { device = "ssd0/freepbx";
      fsType = "zfs";
      options = [ "nofail" ];
    };

  fileSystems."/disks/ssd0/opnsense" =
    { device = "ssd0/opnsense";
      fsType = "zfs";
      options = [ "nofail" ];
    };

  fileSystems."/disks/ssd0/vpnopnsense" =
    { device = "ssd0/vpnopnsense";
      fsType = "zfs";
      options = [ "nofail" ];
    };

  fileSystems."/disks/ssd-raid0-0" =
    { device = "ssd-raid0-0";
      fsType = "zfs";
      options = [ "nofail" ];
    };

  fileSystems."/disks/ssd-raid0-0/minecraft-asstown" =
    { device = "ssd-raid0-0/minecraft-asstown";
      fsType = "zfs";
      options = [ "nofail" ];
    };

  fileSystems."/disks/ssd-raid0-0/minecraft-dnd" =
    { device = "ssd-raid0-0/minecraft-dnd";
      fsType = "zfs";
      options = [ "nofail" ];
    };

  fileSystems."/disks/ssd-raid0-0/minecraft-n-world" =
    { device = "ssd-raid0-0/minecraft-n-world";
      fsType = "zfs";
      options = [ "nofail" ];
    };

  fileSystems."/disks/ssd-raid0-0/minecraft-sadworld" =
    { device = "ssd-raid0-0/minecraft-sadworld";
      fsType = "zfs";
      options = [ "nofail" ];
    };

  fileSystems."/disks/ssd-raid0-0/win-srv-2019" =
    { device = "ssd-raid0-0/win-srv-2019";
      fsType = "zfs";
      options = [ "nofail" ];
    };

  fileSystems."/disks/ssd-raid0-0/win10" =
    { device = "ssd-raid0-0/win10";
      fsType = "zfs";
      options = [ "nofail" ];
    };

  fileSystems."/disks/ssd-raid0-0/macbs" =
    { device = "ssd-raid0-0/macbs";
      fsType = "zfs";
      options = [ "nofail" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/7ff0498b-c609-4a8c-a20c-11b081ba9a8c"; }
    ];

}
